[package]
name = "aurora-engine-migration-tool"
version = "0.2.3"
authors = ["Aurora Labs <hello@aurora.dev>", "Evgeny Ukhanov <evgeny@aurora.dev>"]
edition = "2021"
description = "Aurora Engine migration tools"
documentation = ""
readme = true
homepage = "https://github.com/aurora-is-near/aurora-engine-migration-tool"
repository = "https://github.com/aurora-is-near/aurora-engine-migration-tool"
license = "CC0 1.0"
publish = false
autobenches = false

[dependencies]
aurora-engine-types = { git = "https://github.com/aurora-is-near/aurora-engine.git", tag = "3.8.0", default-features = false }
serde = "1"
serde_json = "1"
serde_derive = "1"
base64 = "0.20"
borsh = "1.5.1"
near-jsonrpc-client = "0.15.0"
near-jsonrpc-primitives = "0.28.0"
near-primitives = "0.28.0"
near-sdk = "5.7.0"
near-lake-framework = "0.7.11"
anyhow = "1.0"
tokio = { version = "1", features = ["full"] }
tokio-stream = "0.1"
futures = "0.3.31"
clap = { version = "4.0", features = ["cargo"] }
near-crypto = "0.28.0"
libc = "0.2"

[features]
mainnet = ["log"]
testnet = ["log"]
localnet = ["log"]
mainnet-archival = ["log"]
log = []

[patch.crates-io]
parity-secp256k1 = { git = 'https://github.com/paritytech/rust-secp256k1', rev = "d05fd8e" }
near-sdk = { git = "https://github.com/aurora-is-near/near-sdk-rs.git", tag = "v4.1.1-fix-deps" }
