---
on:
  push:
    branches:
      - master
name: Build
jobs:
  release:
    name: Release
    runs-on: [self-hosted, heavy]
    steps:
      - name: Potential broken submodules fix
        run: |
          git checkout -f $(git -c user.name=x -c user.email=x@x commit-tree $(git hash-object -t tree /dev/null) < /dev/null) || :
      - name: Clone the repository
        uses: actions/checkout@v3
        name: Cargo build
      - run: cargo build --release
env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0
