---
on:
  push:
    branches:
      - master
      - develop
  pull_request:
    
name: Build
jobs:
  release:
    name: Release
    runs-on: [self-hosted, heavy]
    steps:
      - name: Clone the repository
        uses: actions/checkout@v3
      - name: Cargo build
        run: cargo build --release

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0
