---
on:
  push:
    branches:
      - master
      - develop
  pull_request:

name: Lints
jobs:
  fmt:
    name: Format
    runs-on: [self-hosted, light]
    steps:
      - name: Clone the repository
        uses: actions/checkout@v2
      - name: Run cargo fmt
        run: cargo fmt -- --check
  clippy:
    name: Clippy
    runs-on: [self-hosted, heavy]
    steps:
      - name: Clone the repository
        uses: actions/checkout@v3
      - name: Run cargo clippy
        run: cargo clippy -- -D warnings
